"use client";

import { useState } from "react";

const measures = [
  {
    id: "revenue",
    label: "Revenue",
    values: [81462, 96773],
    change: "+19%",
    note: "Sales expanded. This is the number that makes the year look stronger at first glance.",
  },
  {
    id: "operating-income",
    label: "Operating income",
    values: [13656, 8891],
    change: "−35%",
    note: "The business earned less from operations despite recording more revenue.",
  },
  {
    id: "operating-cash",
    label: "Operating cash flow",
    values: [14724, 13256],
    change: "−10%",
    note: "Cash generated by operations weakened. This is a flow during the year, not the year-end cash balance.",
  },
  {
    id: "cash-after-capex",
    label: "Cash after capex",
    values: [7566, 4358],
    change: "−42%",
    note: "Our simple calculation subtracts reported property-and-equipment purchases from operating cash flow.",
  },
] as const;

export function CashFlowLens() {
  const [selected, setSelected] = useState<(typeof measures)[number]["id"]>("revenue");
  const measure = measures.find((item) => item.id === selected) ?? measures[0];
  const largest = Math.max(...measure.values);

  return (
    <figure className="cash-lens" aria-label="Compare Tesla financial measures in 2022 and 2023">
      <div className="cash-lens-heading">
        <div>
          <span className="eyebrow">2022 → 2023 · TESLA</span>
          <h3>Same company. Different story.</h3>
        </div>
        <span className="cash-lens-unit">USD MILLIONS</span>
      </div>
      <div className="cash-lens-controls" role="group" aria-label="Choose a financial measure">
        {measures.map((item) => (
          <button
            type="button"
            key={item.id}
            aria-pressed={selected === item.id}
            onClick={() => setSelected(item.id)}
          >
            {item.label}
          </button>
        ))}
      </div>
      <div className="cash-lens-chart" aria-live="polite">
        <div className="cash-lens-chart-top">
          <strong>{measure.label}</strong>
          <span>{measure.change}</span>
        </div>
        {measure.values.map((value, index) => (
          <div className="cash-lens-row" key={index}>
            <span>{2022 + index}</span>
            <div className="cash-lens-track" aria-hidden="true">
              <div style={{ width: `${Math.round((value / largest) * 100)}%` }} />
            </div>
            <strong>{value.toLocaleString("en-US")}</strong>
          </div>
        ))}
        <p>{measure.note}</p>
      </div>
      <figcaption>
        Source: <a href="https://www.sec.gov/Archives/edgar/data/1318605/000162828024002390/tsla-20231231.htm" target="_blank" rel="noopener noreferrer">Tesla 2023 Form 10-K</a>. Changes rounded; cash after capex is calculated as described in the table below.
      </figcaption>
    </figure>
  );
}
